# Generated by Django 2.0.10 on 2019-01-23 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('status', models.CharField(choices=[('CONFIRMED', 'Si Asistire'), ('DECLINED', 'No Asistire')], max_length=9)),
                ('meal', models.CharField(choices=[(1, 'Meal Option 1'), (2, 'Meal Option 2'), (3, 'Meal Option 3')], max_length=1)),
                ('notes', models.TextField()),
                ('rsvp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='snorlax.Person')),
            ],
        ),
        migrations.AddField(
            model_name='familygroup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snorlax.Person'),
        ),
    ]
