# Generated by Django 2.0.10 on 2019-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorlax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familygroup',
            name='member',
        ),
        migrations.AddField(
            model_name='familygroup',
            name='member',
            field=models.ManyToManyField(to='snorlax.Person'),
        ),
    ]
