# Generated by Django 2.0.10 on 2019-01-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorlax', '0004_auto_20190123_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='meal',
            field=models.CharField(choices=[(1, 'Meal Option 1'), (2, 'Meal Option 2'), (3, 'Meal Option 3')], max_length=20),
        ),
    ]
