# Generated by Django 2.0.10 on 2019-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorlax', '0006_auto_20190123_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Accept'), ('DECLINED', 'Decline')], max_length=9),
        ),
    ]
