# Generated by Django 2.0.10 on 2019-01-25 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snorlax', '0007_auto_20190123_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confirmation_status',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='member',
            field=models.ManyToManyField(to='snorlax.Person', verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='meal',
            field=models.CharField(choices=[('MEAL_1', 'Meal Option 1'), ('MEAL_2', 'Meal Option 2'), ('MEAL_3', 'Meal Option 3')], max_length=20, verbose_name='meal options'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='notes',
            field=models.TextField(blank=True, verbose_name='dietary restrictions'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='snorlax.Person', verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='rsvp_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='RSVP date'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Accept'), ('DECLINED', 'Decline')], max_length=9, verbose_name='status'),
        ),
    ]
