# Generated by Django 2.0.10 on 2019-01-26 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snorlax', '0008_auto_20190125_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
