# Generated by Django 2.0.10 on 2019-02-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snorlax', '0010_auto_20190127_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='meal',
            field=models.CharField(choices=[('MEAL_1', 'Meal Option 1'), ('MEAL_2', 'Meal Option 2'), ('MEAL_3', 'Meal Option 3'), ('MEAL_4', 'Meal Option 4'), ('MEAL_5', 'Meal Option 5'), ('MEAL_6', 'Meal Option 6'), ('MEAL_7', 'Meal Option 7')], default='MEAL_1', max_length=20, verbose_name='meal options'),
        ),
    ]
